config/routes.rb
Rails.application.routes.draw do
  resources :weekly_progresses, only: [:new, :edit, :create, :update]
  resources :key_results, only: [:new, :edit, :create, :update, :destroy]
  resources :objectives
  resources :organizations
  root 'objectives#index'
end

app/models/objective.rb
class Objective < ApplicationRecord
  belongs_to :organization, optional: false
  belongs_to :objective, optional: true
  validates :description, :year, :quarter, presence: true

  def to_s
    "#{description}"
  end
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
  before_action :set_objective, only: [:show, :edit, :update, :destroy]

  # GET /objectives
  # GET /objectives.json
  def index
    @objectives = Objective.all
    @root_node = nil

    nodes_data = Hash.new
    nodes_relationships = Hash.new

    @objectives.each do |objective|
      node = {"description" => objective.description, "children" => [], "id" => objective.id}
      nodes_data[objective.id] = node

      if objective.objective_id == nil
        @root = node
      else
        if !nodes_relationships.key?(objective.objective_id)
          nodes_relationships[objective.objective_id] = Array.new
        end

        nodes_relationships[objective.objective_id].push(objective.id)
      end
    end

    if !@root.nil?
      parse_orgchart_relationships(@root, nodes_relationships, nodes_data)
    end
  end

  # GET /objectives/1
  # GET /objectives/1.json
  def show
    @key_results = KeyResult.where(objective_id: @objective.id).all
    @weeks = get_quarter_weeks(@objective.year, @objective.quarter)
    @progresses = Hash.new

    @key_results.each do |key_result|
      @progresses[key_result.id] = Hash.new

      @kr_progresses = WeeklyProgress.where(key_result_id: key_result.id).all
      @kr_progresses.each do |kr_progress|
        @progresses[key_result.id][kr_progress.week] = kr_progress
      end
    end
  end

  # GET /objectives/new
  def new
    @objective = Objective.new
  end

  # GET /objectives/1/edit
  def edit
  end

  # POST /objectives
  # POST /objectives.json
  def create
    @objective = Objective.new(objective_params)

    respond_to do |format|
      if @objective.save
        format.html { redirect_to @objective, notice: 'Objective was successfully created.' }
        format.json { render :show, status: :created, location: @objective }
      else
        format.html { render :new }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /objectives/1
  # PATCH/PUT /objectives/1.json
  def update
    respond_to do |format|
      if @objective.update(objective_params)
        format.html { redirect_to @objective, notice: 'Objective was successfully updated.' }
        format.json { render :show, status: :ok, location: @objective }
      else
        format.html { render :edit }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objectives/1
  # DELETE /objectives/1.json
  def destroy
    @objective.destroy
    respond_to do |format|
      format.html { redirect_to objectives_url, notice: 'Objective was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_objective
      @objective = Objective.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def objective_params
      params.require(:objective).permit(:description, :organization_id, :objective_id, :year, :quarter)
    end

  def parse_orgchart_relationships(node, relationships, nodes)
    if relationships.has_key?(node["id"])
      relationships[node["id"]].each do |child_node|
        child_node = nodes[child_node].clone()
        parse_orgchart_relationships(child_node, relationships, nodes)
        node["children"].push(child_node)
      end
    end
  end

  def get_quarter_weeks(year, quarter)
    weeks = Array.new

    start_month = ((quarter - 1) * 3) + 1
    end_month = start_month + 2
    current_week = Date.new year, start_month, 1

    if current_week.cwday > 1
      current_week = current_week + ((7 - current_week.cwday) + 1)
    end

    loop do
      weeks.push(current_week)
      current_week = current_week + 7

      break if current_week.month > end_month || current_week.year > year
    end

    weeks
  end

end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/views/objectives/_form.html.erb
<%= form_for(objective) do |f| %>
  <% if objective.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(objective.errors.count, "error") %> prohibited this objective from being saved:</h2>

      <ul>
      <% objective.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :year %>
    <%= f.text_field :year, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :quarter %>
    <%= f.text_field :quarter, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :organization_id %>
    <%= collection_select(:objective, :organization_id, Organization.all, :id, :name, {prompt: true}, {class: "form-control"}) %>
  </div>

  <div class="form-group">
    <%= f.label "Parent objective" %>
    <%= collection_select(:objective, :objective_id, Objective.all, :id, :description, {prompt: "Leave blank for root objective"}, {class: "form-control"}) %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/objectives/edit.html.erb
<h1>Editing Objective</h1>

<%= render 'form', objective: @objective %>

<%= link_to 'Show', @objective %> |
<%= link_to 'Back', objectives_path %>

app/views/objectives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Objectives</h1>

<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Organization</th>
      <th>Year</th>
      <th>Quarter</th>
      <th>Parent objective</th>
      <th colspan="3" width="10%"></th>
    </tr>
  </thead>

  <tbody>
    <% @objectives.each do |objective| %>
      <tr>
        <td><%= objective.description %></td>
        <td><%= objective.organization %></td>
        <td><%= objective.year %></td>
        <td><%= objective.quarter %></td>
        <td><%= objective.objective %></td>
        <td><%= link_to 'Show', objective %></td>
        <td><%= link_to 'Edit', edit_objective_path(objective) %></td>
        <td><%= link_to 'Destroy', objective, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Objective', new_objective_path, class: "btn btn-primary" %>

<div class="row" id="orgchart-container" style="margin-top: 50px; text-align: center;">
</div>

<script>
  var dataSource = <%= @root.to_json.html_safe %>;
  $('#orgchart-container').orgchart({
    'data' : dataSource,
    'nodeTitle': 'description',
    'chartClass': 'orgchart-container',
    'createNode': function($node, data) {
      $node.on('click', function() {
        window.location.href = "/objectives/" + data["id"];
      });
    }
  });
</script>

app/views/objectives/new.html.erb
<h1>New Objective</h1>

<%= render 'form', objective: @objective %>

<%= link_to 'Back', objectives_path %>

app/views/objectives/show.html.erb
<p id="notice"><%= notice %></p>

  <h1>Objective: <%= @objective.description; %></h1>

<div class="panel panel-default">
  <div class="panel-body">
    <p>
      <strong>Year:</strong>
      <%= @objective.year %>
    </p>

    <p>
      <strong>Quarter:</strong>
      Q<%= @objective.quarter %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @objective.description %>
    </p>

    <p>
      <strong>Organization:</strong>
      <%= @objective.organization %>
    </p>

    <p><%= link_to 'Edit', edit_objective_path(@objective) %></p>
  </div>
</div>

<%= link_to 'New Key Result', new_key_result_path(:objective => @objective), class: "btn btn-primary" %>

<% @key_results.each do |key_result| %>
  <div class="page-header">
    <h2>
      Key result: <%= key_result.description %>
    </h2>
  </div>
  <div class="table-responsive">
    <table class="table table-striped" id="weekly-progress-table">
      <thead>
        <tr>
          <% @weeks.each do |week| %>
            <th>Week <%= week.cweek %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <tr>
          <% @weeks.each do |week| %>
            <td>
              <% if @progresses[key_result.id].key?(week.cweek) %>
                <% progress = @progresses[key_result.id][week.cweek] %>
                <% label = if progress.progress > 75 then "label-success" elsif progress.progress > 30 then "label-warning" else "label-danger" end %>
                <a href="<%= edit_weekly_progress_path(progress) %>" class="edit-progress-btn">
                  <span class="label <%= label %>">Progress: <%= progress.progress %>%</span>
                </a>
              <% else %>
                <a href="<%= new_weekly_progress_path(:week => week.cweek, :year => @objective.year, :key_result => key_result) %>">
                  <span class="label label-default">Progress: --</span>
                </a>
              <% end %>
            </td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>

  <%= link_to 'Edit this key result', edit_key_result_path(key_result), class: "btn btn-xs btn-default" %>
  <%= link_to 'Remove this key result', key_result, method: :delete, class: "btn btn-xs btn-default", data: { confirm: 'Are you sure?' } %>
<% end %>